---
# tasks file for dotnet

- name: get dotnet dpkg
  apt:
    deb: "https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb"

- name: install dotnet sdk
  apt:
    name: dotnet-sdk-5.0
    update_cache: true
