---
# tasks file for py

- name: python environment
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-dev
    - python3-pip
    - virtualenv
    - python3-setuptools
    - pipenv
